-- Get the survey IDs first (run after inserting surveys above)
-- Then add questions for each survey

-- Questions for "Online Shopping Preferences" (Survey 1)
INSERT INTO public.survey_questions (survey_id, question_text, question_type, options, question_order, is_required) VALUES
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'How often do you shop online?', 'single_choice', '[{"value":"daily","label":"Daily"},{"value":"weekly","label":"Weekly"},{"value":"monthly","label":"Monthly"},{"value":"rarely","label":"Rarely"},{"value":"never","label":"Never"}]', 1, true),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'What products do you buy most online?', 'multiple_choice', '[{"value":"electronics","label":"Electronics"},{"value":"clothing","label":"Clothing"},{"value":"food","label":"Food/Groceries"},{"value":"books","label":"Books"},{"value":"home","label":"Home items"}]', 2, true),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'Which platform do you use most?', 'single_choice', '[{"value":"jumia","label":"Jumia"},{"value":"kilimall","label":"Kilimall"},{"value":"amazon","label":"Amazon"},{"value":"facebook","label":"Facebook Marketplace"},{"value":"instagram","label":"Instagram Shops"}]', 3, true),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'What influences your purchase decision?', 'multiple_choice', '[{"value":"price","label":"Price"},{"value":"reviews","label":"Customer Reviews"},{"value":"brand","label":"Brand Reputation"},{"value":"delivery","label":"Delivery Speed"},{"value":"discounts","label":"Discounts/Offers"}]', 4, true),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'How much do you spend monthly on online shopping?', 'single_choice', '[{"value":"under1k","label":"Under KSH 1,000"},{"value":"1to5k","label":"KSH 1,000 - 5,000"},{"value":"5to10k","label":"KSH 5,000 - 10,000"},{"value":"10to20k","label":"KSH 10,000 - 20,000"},{"value":"over20k","label":"Over KSH 20,000"}]', 5, true),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'What payment method do you prefer?', 'single_choice', '[{"value":"mpesa","label":"M-Pesa"},{"value":"card","label":"Credit/Debit Card"},{"value":"cod","label":"Cash on Delivery"},{"value":"bank","label":"Bank Transfer"}]', 6, true),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'Have you ever returned an online purchase?', 'single_choice', '[{"value":"yes","label":"Yes"},{"value":"no","label":"No"},{"value":"multiple","label":"Multiple times"}]', 7, true),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'What would improve your online shopping experience?', 'text', '[]', 8, false);

-- Questions for "Mobile App Experience" (Survey 2)
INSERT INTO public.survey_questions (survey_id, question_text, question_type, options, question_order, is_required) VALUES
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'How many apps do you have on your phone?', 'single_choice', '[{"value":"less20","label":"Less than 20"},{"value":"20to50","label":"20-50"},{"value":"50to100","label":"50-100"},{"value":"more100","label":"More than 100"}]', 1, true),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'Which app category do you use most?', 'single_choice', '[{"value":"social","label":"Social Media"},{"value":"banking","label":"Banking/Finance"},{"value":"shopping","label":"Shopping"},{"value":"entertainment","label":"Entertainment"},{"value":"productivity","label":"Productivity"}]', 2, true),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'How often do you download new apps?', 'single_choice', '[{"value":"weekly","label":"Weekly"},{"value":"monthly","label":"Monthly"},{"value":"rarely","label":"Rarely"},{"value":"whenneeded","label":"Only when needed"}]', 3, true),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'What makes you uninstall an app?', 'multiple_choice', '[{"value":"slow","label":"Too slow"},{"value":"ads","label":"Too many ads"},{"value":"storage","label":"Takes too much storage"},{"value":"battery","label":"Drains battery"},{"value":"privacy","label":"Privacy concerns"}]', 4, true),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'Do you read app reviews before downloading?', 'single_choice', '[{"value":"always","label":"Always"},{"value":"sometimes","label":"Sometimes"},{"value":"never","label":"Never"}]', 5, true),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'Have you paid for any app or in-app purchase?', 'single_choice', '[{"value":"yes","label":"Yes"},{"value":"no","label":"No"},{"value":"planning","label":"Planning to"}]', 6, true),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'What feature do you value most in apps?', 'single_choice', '[{"value":"speed","label":"Speed/Performance"},{"value":"design","label":"User-friendly design"},{"value":"offline","label":"Offline functionality"},{"value":"security","label":"Security features"},{"value":"personalization","label":"Personalization"}]', 7, true),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'Any app recommendations or feedback?', 'text', '[]', 8, false);

-- Questions for "Digital Payment Methods" (Survey 3)
INSERT INTO public.survey_questions (survey_id, question_text, question_type, options, question_order, is_required) VALUES
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'Which digital payment do you use most?', 'single_choice', '[{"value":"mpesa","label":"M-Pesa"},{"value":"bankapp","label":"Bank App"},{"value":"paypal","label":"PayPal"},{"value":"card","label":"Card Payment"},{"value":"crypto","label":"Cryptocurrency"}]', 1, true),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'How often do you use digital payments?', 'single_choice', '[{"value":"multiple","label":"Multiple times daily"},{"value":"daily","label":"Daily"},{"value":"weekly","label":"Weekly"},{"value":"monthly","label":"Monthly"},{"value":"rarely","label":"Rarely"}]', 2, true),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'What do you pay for most with digital payments?', 'multiple_choice', '[{"value":"bills","label":"Utility Bills"},{"value":"shopping","label":"Shopping"},{"value":"transfers","label":"Money Transfers"},{"value":"subscriptions","label":"Subscriptions"},{"value":"food","label":"Food Delivery"}]', 3, true),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'What is your biggest concern with digital payments?', 'single_choice', '[{"value":"security","label":"Security/Fraud"},{"value":"fees","label":"Transaction Fees"},{"value":"network","label":"Network Issues"},{"value":"limits","label":"Transaction Limits"},{"value":"privacy","label":"Privacy"}]', 4, true),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'Have you ever had a failed transaction?', 'single_choice', '[{"value":"yes","label":"Yes"},{"value":"no","label":"No"},{"value":"multiple","label":"Multiple times"}]', 5, true),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'How quickly are your issues resolved?', 'single_choice', '[{"value":"immediate","label":"Immediately"},{"value":"hours","label":"Within hours"},{"value":"days","label":"1-2 days"},{"value":"week","label":"Longer than a week"},{"value":"never","label":"Never resolved"}]', 6, true),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'Would you recommend your payment provider?', 'single_choice', '[{"value":"definitely","label":"Definitely"},{"value":"probably","label":"Probably"},{"value":"notsure","label":"Not sure"},{"value":"probablynot","label":"Probably not"},{"value":"definitelynot","label":"Definitely not"}]', 7, true),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'What improvements would you suggest?', 'text', '[]', 8, false);

-- Questions for "Investment Awareness" (Survey 4)
INSERT INTO public.survey_questions (survey_id, question_text, question_type, options, question_order, is_required) VALUES
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'Do you currently invest in any financial instruments?', 'single_choice', '[{"value":"yes","label":"Yes"},{"value":"no","label":"No"},{"value":"planning","label":"Planning to start"}]', 1, true),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'Which investments are you aware of?', 'multiple_choice', '[{"value":"stocks","label":"Stocks/Shares"},{"value":"bonds","label":"Government Bonds"},{"value":"sacco","label":"SACCOs"},{"value":"mmf","label":"Money Market Funds"},{"value":"crypto","label":"Cryptocurrency"},{"value":"realestate","label":"Real Estate"}]', 2, true),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'How much would you consider investing monthly?', 'single_choice', '[{"value":"under5k","label":"Under KSH 5,000"},{"value":"5to10k","label":"KSH 5,000 - 10,000"},{"value":"10to50k","label":"KSH 10,000 - 50,000"},{"value":"50to100k","label":"KSH 50,000 - 100,000"},{"value":"over100k","label":"Over KSH 100,000"}]', 3, true),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'What is your investment goal?', 'single_choice', '[{"value":"shortterm","label":"Short-term gains"},{"value":"longterm","label":"Long-term wealth"},{"value":"retirement","label":"Retirement"},{"value":"emergency","label":"Emergency fund"},{"value":"education","label":"Education"}]', 4, true),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'How do you research investments?', 'multiple_choice', '[{"value":"social","label":"Social Media"},{"value":"friends","label":"Friends/Family"},{"value":"advisor","label":"Financial Advisor"},{"value":"bank","label":"Bank Information"},{"value":"online","label":"Online Research"}]', 5, true),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'What prevents you from investing more?', 'single_choice', '[{"value":"knowledge","label":"Lack of knowledge"},{"value":"funds","label":"Insufficient funds"},{"value":"risk","label":"Fear of losing money"},{"value":"trust","label":"Don''t trust institutions"},{"value":"access","label":"No access to platforms"}]', 6, true),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'Would you use a mobile app for investments?', 'single_choice', '[{"value":"yes","label":"Yes"},{"value":"no","label":"No"},{"value":"maybe","label":"Maybe"}]', 7, true),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'Any questions about investing?', 'text', '[]', 8, false);

-- Questions for "Tech Gadget Usage" (Survey 5)
INSERT INTO public.survey_questions (survey_id, question_text, question_type, options, question_order, is_required) VALUES
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'Which device do you use most daily?', 'single_choice', '[{"value":"smartphone","label":"Smartphone"},{"value":"laptop","label":"Laptop"},{"value":"tablet","label":"Tablet"},{"value":"desktop","label":"Desktop"},{"value":"smartwatch","label":"Smartwatch"}]', 1, true),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'How many tech gadgets do you own?', 'single_choice', '[{"value":"1to2","label":"1-2 devices"},{"value":"3to5","label":"3-5 devices"},{"value":"6to10","label":"6-10 devices"},{"value":"more10","label":"More than 10"}]', 2, true),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'What do you use your devices for most?', 'multiple_choice', '[{"value":"work","label":"Work"},{"value":"entertainment","label":"Entertainment"},{"value":"communication","label":"Communication"},{"value":"learning","label":"Learning"},{"value":"shopping","label":"Shopping"}]', 3, true),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'How often do you upgrade your devices?', 'single_choice', '[{"value":"yearly","label":"Every year"},{"value":"2years","label":"Every 2 years"},{"value":"3years","label":"Every 3+ years"},{"value":"whenbroken","label":"Only when broken"},{"value":"rarely","label":"Rarely upgrade"}]', 4, true),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'What influences your gadget purchase?', 'multiple_choice', '[{"value":"brand","label":"Brand"},{"value":"price","label":"Price"},{"value":"features","label":"Features"},{"value":"reviews","label":"Reviews"},{"value":"warranty","label":"Warranty/Support"}]', 5, true),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'Do you use smart home devices?', 'single_choice', '[{"value":"yes","label":"Yes"},{"value":"no","label":"No"},{"value":"planning","label":"Planning to buy"},{"value":"interested","label":"Interested but expensive"}]', 6, true),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'How much do you spend on tech yearly?', 'single_choice', '[{"value":"under10k","label":"Under KSH 10,000"},{"value":"10to50k","label":"KSH 10,000 - 50,000"},{"value":"50to100k","label":"KSH 50,000 - 100,000"},{"value":"100to200k","label":"KSH 100,000 - 200,000"},{"value":"over200k","label":"Over KSH 200,000"}]', 7, true),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'What tech product are you planning to buy next?', 'text', '[]', 8, false);
